"""Remove foursquare_id from Destinations model, and add is_admin to User model

Revision ID: 6df964d63b79
Revises: fad273cd1b57
Create Date: 2025-06-23 16:38:45.347363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6df964d63b79'
down_revision = 'fad273cd1b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index('ix_destinations_foursquare_id')
        batch_op.drop_column('foursquare_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foursquare_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_index('ix_destinations_foursquare_id', ['foursquare_id'], unique=True)

    # ### end Alembic commands ###
