"""Update column foursquare_id in destination table

Revision ID: fad273cd1b57
Revises: 4cb4d656f311
Create Date: 2025-06-23 15:42:28.043744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fad273cd1b57'
down_revision = '4cb4d656f311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('foursquare_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index('foursquare_id')
        batch_op.create_index(batch_op.f('ix_destinations_foursquare_id'), ['foursquare_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destinations_foursquare_id'))
        batch_op.create_index('foursquare_id', ['foursquare_id'], unique=True)
        batch_op.alter_column('foursquare_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
